language: node_js

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_TOKEN

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - jspm install

script:
  - ./node_modules/.bin/gulp lint
  - ./node_modules/.bin/gulp build
