language: node_js

node_js:
  - "4.1"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1cdf7d782670bd83bedb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_TOKEN

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - jspm install

script:
  - ./node_modules/.bin/gulp

after_success:
  - bash deploy.sh
